### PR TITLE
Bugfix: Apply the changes for updates

### PR DESCRIPTION
**Pull request by Maik7**
If an automation updated its settings, the changes were ignored :-(

### CODE REVIEW

**Comment by Maik7** [comment]
I've updated the fix. Now it should work as expected

**Comment by InventoCasa** [comment]
@Maik7 Can you explain a bit, what excatly the problem was? 
Normally if settings in the blueprint-based automation are changed and the automation is executed again, it should overwrite the previously existing instance right here in the code:
```PvExcessControl.instances[self.automation_id] = {'instance': self, 'priority': self.appliance_priority}```

**Comment by Maik7** [comment]
Hi,That line is not reached, if you update the parameters, asself.automation_id not in PvExcessControl.instancesIs not true GrüßeMaik

**Comment by InventoCasa** [comment]
> Hi,That line is not reached, if you update the parameters, asself.automation_id not in PvExcessControl.instancesIs not true GrüßeMaik

Ah, you're right. Merging the changes now.

**Pull request merged**
