### PR TITLE
pyscript: Track daily running time

### PR DESCRIPTION
**Pull request by alistair23**
This is the first step in addressing
https://github.com/InventoCasa/ha-advanced-blueprints/issues/32.

This patch adds support to monitor the total daily runtime of appliances and prints the information to the user.

### CODE REVIEW

**Comment by Verpz** [comment]
Would be cool if there was also a sensor to track this.

**Comment by alistair23** [comment]
> Would be cool if there was also a sensor to track this.

That would be cool! Any idea how to do that?

**Comment by Verpz** [comment]
> > Would be cool if there was also a sensor to track this.
> 
> That would be cool! Any idea how to do that?

[History Stats](https://www.home-assistant.io/integrations/history_stats/) 

History stats has been working well for me! It is already built-in

**Comment by alistair23** [comment]
The part I'm not sure how to do is expose it from pyscript

**Review by Kolbi — APPROVED** [review]
Looks good for me.

**Review by Kolbi — APPROVED** [review]

**Comment by Kolbi** [comment]
@InventoCasa did you had a chance to review this PR?

**Comment by InventoCasa** [comment]
Well, better late than never, right?
@alistair23 Thanks for the PR! I reviewed it. I vow to do better with future PRs (in terms of processing time) ;)

**Pull request merged**
